### Neues Projekt erstellen
POST http://localhost:8080/projects
Content-Type: application/json

{
  "designation": "Neues Projekt",
  "responsibleEmployeeId": 1,
  "customerId": 1,
  "customerContactPerson": "Max Mustermann",
  "comment": "Dies ist ein neues Projekt",
  "startDate": "2025-10-01",
  "plannedEndDate": "2026-03-31"
}


### Projekt abrufen
GET http://localhost:8080/projects/1
Content-Type: application/json


### Alle Projekte auflisten
GET http://localhost:8080/projects
Content-Type: application/json


### Projekt aktualisieren
PUT http://localhost:8080/projects/1
Content-Type: application/json

{
  "designation": "Aktualisiertes Projekt",
  "responsibleEmployeeId": 2,
  "customerId": 2,
  "customerContactPerson": "Neue Person",
  "comment": "Aktualisierter Kommentar",
  "startDate": "2025-12-01",
  "plannedEndDate": "2026-06-30"
}


### Projekt löschen
DELETE http://localhost:8080/projects/1
Content-Type: application/json


### Mitarbeiter einem Projekt zuweisen
POST http://localhost:8080/projects/1/employees
Content-Type: application/json

{
  "employeeId": 1,
  "qualification": "Java"
}


### Mitarbeiter von einem Projekt entfernen
DELETE http://localhost:8080/projects/1/employees/1
Content-Type: application/json
